package com.ermukhamed.deepresearch.output

import com.ermukhamed.deepresearch.agent.ResearchReport
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import java.time.format.DateTimeFormatter

/** Serialises a [ResearchReport] into one concrete output format. */
fun interface ReportRenderer {
    fun render(report: ResearchReport): String

    companion object {
        /** Returns the renderer that produces [format]. */
        fun forFormat(format: OutputFormat): ReportRenderer = when (format) {
            OutputFormat.MARKDOWN -> MarkdownRenderer
            OutputFormat.JSON -> JsonRenderer
            OutputFormat.RAW -> RawRenderer
        }
    }
}

/** The model's text verbatim — suitable for piping into another tool. */
object RawRenderer : ReportRenderer {
    override fun render(report: ResearchReport): String = report.content
}

/** The report under a title, with a provenance footer. */
object MarkdownRenderer : ReportRenderer {
    private val TIMESTAMP: DateTimeFormatter = DateTimeFormatter.ISO_INSTANT

    override fun render(report: ResearchReport): String = buildString {
        appendLine("# Research: ${report.query}")
        appendLine()
        appendLine(report.content.trim())
        appendLine()
        appendLine("---")
        appendLine()
        appendLine("*Generated by [DeepResearchAiAgent](https://github.com/ermawqa/DeepResearchAIAgent) " +
            "using `${report.model}` on ${TIMESTAMP.format(report.generatedAt)}.*")
        report.usage?.let {
            appendLine()
            appendLine("*Tokens: ${it.promptTokens} prompt + ${it.completionTokens} completion " +
                "= ${it.totalTokens} total.*")
        }
    }
}

/** A stable JSON record, safe to archive or feed to downstream tooling. */
object JsonRenderer : ReportRenderer {
    private val mapper: ObjectMapper = jacksonObjectMapper()

    override fun render(report: ResearchReport): String {
        val payload = linkedMapOf<String, Any?>(
            "query" to report.query,
            "model" to report.model,
            "generated_at" to report.generatedAt.toString(),
            "content" to report.content,
            "usage" to report.usage?.let {
                linkedMapOf(
                    "prompt_tokens" to it.promptTokens,
                    "completion_tokens" to it.completionTokens,
                    "total_tokens" to it.totalTokens,
                )
            },
        )
        return mapper.writerWithDefaultPrettyPrinter().writeValueAsString(payload)
    }
}
